# Generated by Django 2.2.2 on 2021-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210702_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
