# Generated by Django 2.2.2 on 2021-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210702_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='received_amount',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
