# Generated by Django 2.2.2 on 2021-07-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210709_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='rds0751@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
