# Generated by Django 2.2.13 on 2021-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
