# Generated by Django 2.2.13 on 2021-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='traditional_withdrawal',
            field=models.FloatField(default=0),
        ),
    ]
