# Generated by Django 2.2.13 on 2022-02-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_traditional_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dcxa_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
