# Generated by Django 2.2.2 on 2021-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertotal',
            old_name='user_id',
            new_name='direct',
        ),
        migrations.AddField(
            model_name='levelincomesettings',
            name='direct_commission_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertotal',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertotal',
            name='user',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
