# Generated by Django 2.2.2 on 2021-07-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_auto_20210702_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertotal',
            name='active_users',
        ),
        migrations.RemoveField(
            model_name='usertotal',
            name='inactive_users',
        ),
    ]
