# Generated by Django 2.2.2 on 2021-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_auto_20210702_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelincomesettings',
            name='expiration_period',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertotal',
            name='left_months',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
