# Generated by Django 2.2.2 on 2021-07-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_auto_20210702_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertotal',
            old_name='level',
            new_name='amount',
        ),
    ]
