# Generated by Django 2.2.2 on 2021-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_auto_20210704_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertotal',
            old_name='amount',
            new_name='level',
        ),
    ]
