# Generated by Django 2.2.2 on 2021-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0006_auto_20210707_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotal',
            name='business',
            field=models.IntegerField(default=0),
        ),
    ]
