# Generated by Django 2.2.2 on 2021-07-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_usertotal_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotal',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.LevelIncomeSettings'),
        ),
    ]
