# Generated by Django 2.2.2 on 2021-07-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_auto_20210713_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelincomesettings',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='image',
            field=models.FileField(null=True, upload_to='activation/'),
        ),
    ]
