# Generated by Django 2.2.2 on 2021-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0009_auto_20210713_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotal',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
