# Generated by Django 2.2.2 on 2021-07-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeHistory',
        ),
        migrations.DeleteModel(
            name='Mainwallets',
        ),
        migrations.DeleteModel(
            name='MoneyTransfers',
        ),
        migrations.DeleteModel(
            name='Recharges',
        ),
        migrations.DeleteModel(
            name='UserSchedulePayments',
        ),
        migrations.AddField(
            model_name='paymentoptions',
            name='mt5_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
