# Generated by Django 2.2.2 on 2021-07-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210703_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddMoney',
            new_name='AddFund',
        ),
        migrations.RenameModel(
            old_name='Paymentoptions',
            new_name='PaymentOption',
        ),
        migrations.RenameModel(
            old_name='WalletHistories',
            new_name='WalletHistory',
        ),
        migrations.RenameModel(
            old_name='Withdrawals',
            new_name='Withdrawal',
        ),
        migrations.RenameField(
            model_name='wallethistory',
            old_name='balance_after',
            new_name='balance',
        ),
    ]
