# Generated by Django 2.2.2 on 2021-07-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_fundrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoption',
            old_name='upi_id',
            new_name='bank',
        ),
    ]
