# Generated by Django 2.2.2 on 2021-07-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(max_length=20, unique=True)),
                ('imageP', models.ImageField(upload_to='')),
                ('imageAF', models.ImageField(upload_to='')),
                ('imageAB', models.ImageField(upload_to='')),
                ('pan', models.CharField(max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.NullBooleanField()),
            ],
        ),
    ]
