# Generated by Django 2.2.2 on 2021-07-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='imageP',
        ),
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='pan',
        ),
    ]
